[Interface]
PrivateKey = EBgbFrztNldFhXNARjEnUFn/JlPyeNAJArMuw54MJ0A=
Address = 10.66.66.101/32
DNS = 1.1.1.1

[Peer]
PublicKey = h0KlxnpuDniXZpT6vW21EvcSK8uaY7noxN8L7JbzHQo=
Endpoint = 52.56.145.153:22160
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
